### ISSUE TITLE
Tail_n_mail not excluding the string(s)

### ISSUE THREAD

**Issue by smithapamujula** [bucardo/tail_n_mail#10]
Hello,

I am using tail_n_mail-1.26.0-1 for my postgres systems. I have two conf files one for emailing and one for paging. I have two cron jobs that run in 10 minute interval one using email.conf and one using oncall.conf.

I have a lot of INCLUDE: and EXCLUDE: in the conf files. But it doesnt seem to be excluding the lines/strings. Can you please tell me what I am doing wrong. Really appreciate your help.

Thanks
Smitha 

Here is the sample of the conf file. 
INCLUDE: ERROR:  
INCLUDE: FATAL:  
INCLUDE: PANIC:  
INCLUDE: SIGHUP 
INCLUDE: temporary file: path
INCLUDE: archive command failed
INCLUDE: could not be archived
INCLUDE: transaction ID wrap limit
INCLUDE: must be vacuumed within
INCLUDE: terminated
INCLUDE: Segmentation fault
INCLUDE: is missing
EXCLUDE: database ".+" does not exist
EXCLUDE: INFO:
EXCLUDE: CONTEXT:
EXCLUDE: PL/pgSQL function
EXCLUDE: NOTICE:
EXCLUDE: function inline_code_block
EXCLUDE: skipping
EXCLUDE: CONTEXT: SQL statement
EXCLUDE: trust_for_each_subscriber
EXCLUDE_PREFIX: CONTEXT:
EXCLUDE_PREFIX: NOTICE:
EXCLUDE_PREFIX: PL/pgSQL function

**Comment by turnstep** [comment]
Closing due to non-response. Please feel free to reopen as needed.
