### ISSUE TITLE
User and database names containing hyphens break log parsing

### ISSUE THREAD

**Issue by phinjensen** [bucardo/tail_n_mail#12]
ID: 113
Version: unspecified
Date: 2012-09-24 08:30 EDT
Author: Jan Urbański (wulczer@wulczer.org)

---

https://gist.github.com/uncleshelby/5852212
patch to fix the issue

The regexp used to capture %u and %d sequences does not allow hyphens.

The attached patch fixes this and includes a test case to demonstrate the issue
(the test case also shows a different bug, that will be filed separately).

**Comment by turnstep** [comment]
Closing; this was applied in b6df29c9e84d0df1ba675f3fb16b77f5bc4e1ab9 and released in version 1.27.0
