### ISSUE TITLE
log_line_prefix starting with a bracket causes an error

### ISSUE THREAD

**Issue by phinjensen** [bucardo/tail_n_mail#13]
ID: 114
Version: unspecified
Date: 2012-09-24 08:35 EDT
Author: Jan Urbański (wulczer@wulczer.org)

---

The code responsible for capturing log lines from system messages does not
escape metacharacters before trying to interpret the constructed string as a
regexp.

The attached patch fixes this problem. A test case for this issue and #12 has
been attached to #12.

**Comment by turnstep** [comment]
This should be working as expected now.
