### ISSUE TITLE
STATEMENT_SIZE lost during config file rewriting

### ISSUE THREAD

**Issue by gp4git** [bucardo/tail_n_mail#20]
In my config file, I use the following option :
STATEMENT_SIZE : 3000
However, it is lost during config file rewriting.
## Workaround : add --statement_size=3000 on the command line.

Regards

**Comment by turnstep** [comment]
Thanks for the report: fixed in 1d3d2aa5b08f63974fbf8cf0ee8b767802db234e, will be in version 1.29.0
