### ISSUE TITLE
cannot handle session id %c in log_line_prefix

### ISSUE THREAD

**Issue by achix** [bucardo/tail_n_mail#29]
For some reason : (\S+) cannot match session ids like : 5b6c0838.1de3c 
therefore no ERROR or other configured messages are identified.

By removing %c from postgresql log_line_prefix (and adjusting of course LOG_LINE_PREFIX: in tnm conf file) everything works again.

**Comment by turnstep** [comment]
I'm not sure why that is not working: could you show us the conf file you were using, plus the first few lines of running tail_n_mail against that config file with the --verbose argument?

**Comment by achix** [comment]
Hello,
this is the conf file : 
`$ cat ./src/tail_n_mail/tnm.conf
## Config file for the tail_n_mail program
## This file is automatically updated
## Last updated: Fri May  3 08:40:01 2019
##LOG_LINE_PREFIX: '%r [%p] %m '
LOG_LINE_PREFIX: '%r [%p] %c %m %a %u@%d line:%l '
#LOG_LINE_PREFIX: '%r [%p] %m %a %u@%d line:%l '
EMAIL: itdev@itdevel.internal.net, mantzios.achill@gmail.com, trigger_chk_pg_log_repl
MAILSUBJECT: LOGICAL REPLICATION TEST DB Postgres errors UNIQUE : NUMBER

#INCLUDE: ERROR:  
INCLUDE: ERROR:  .*publisher.*
INCLUDE: ERROR:  .*exited with exit.*
INCLUDE: LOG:  .*exited with exit.*
INCLUDE: FATAL:  
INCLUDE: PANIC:  


FILE1: /var/lib/pgsql/data/log/postgresql-%d.log
LASTFILE1: /var/lib/pgsql/data/log/postgresql-03.log
ROTATEFILEMODTIME1:  
OFFSET1: 13738
`

$ ./src/tail_n_mail/tail_n_mail --verbose ./src/tail_n_mail/tnm.conf-with-c 
  Log line prefix regex 0/1: (?^:^(\S* \[(\d+)\] ([a-zA-Z0-9.]+) (\d\d\d\d-\d\d-\d\d \d\d:\d\d:\d\d\.\d+ \w\w\w\w?) .*? [\[\w\-\.\]]*@[\[\w\-\.\]]* line:\d+ )(.*))
  Log line prefix regex 0/2: (?^:^ \[\d+\] %c \d\d\d\d-\d\d-\d\d \d\d:\d\d:\d\d\.\d+ \w\w\w\w? %a @ line:\d+ )
  Log line prefix regex 0/3: (?^:^ \[\d+\] %c \d\d\d\d-\d\d-\d\d \d\d:\d\d:\d\d\.\d+ \w\w\w\w? %a @ line:\d+ )
  File: /var/lib/pgsql/data/log/postgresql-03.log Offset: 15,227 Size: 15,227 Maxsize: 80,000,000

**Comment by achix** [comment]
Have you tested it and it works?

**Comment by turnstep** [comment]
Ah, okay, it was because you were using both %p and %c. I made some changes in HEAD so tings should work now with both set. Please confirm if it is working for your setup now.

**Comment by achix** [comment]
great thanx, will do so when time permits.

**Comment by achix** [comment]
Hello,
seems to work! thanx!

**Comment by achix** [comment]
Hello,
seems to work! thanx!
