### ISSUE TITLE
tail_n_mail does not accept different timezone formats

### ISSUE THREAD

**Issue by andrusbate** [bucardo/tail_n_mail#31]
Hello,

I am using tail_n_mail-1.27.0.-1.sles12.noarch on linux SLES12 SP2.
I configured LOG_LINE_PREFIX equal to log_prefix_line for postgresql logs as '%t %e'.
So tail_n_mail was able to parse all necessary entries starting by timestamp an SQLSTATE type of:
2018-11-21 12:41:32 FET 00000 LOG:  worker process: logical replication worker for subscription 16386 (PID 31777) exited with exit code 1

But after I have updated my SLES12 to SP3 tail_n_mail stopped noticing these entries.
2018-11-21 12:41:32 +03 00000 LOG:  worker process: logical replication worker for subscription 16386 (PID 31777) exited with exit code 1

As you can see the reason is in different output of timezone. FET was before and +03 is our current format.
As far as I understand postgreSQL uses system default configuration and it is not possible to configure some particular timestamp format within PostgreSQL. So, I reckon, it can be corrected in tail_n_mail.

I see in tail_n_mail template that if log contains timestamp, timezone is supposed to be corresponding to 
**\w\w\w\w?** pattern. 
I would suggest changing this part of template by **[+-]?\w+**

Thank You in advance,
Andrei

**Comment by wkk1020** [comment]
Hi there, having same problem here, did you have any workaround?

Thank you.

Regards,
Mike Yeap

**Comment by turnstep** [comment]
Thanks for raising this issue. Please see if commit c12a779a6db3e1e831084810e12abc40d2ded889 fixes the problem for you.

**Comment by turnstep** [comment]
Closing
