### ISSUE TITLE
Do not get any mail using tail_n_mail 

### ISSUE THREAD

**Issue by darshansh** [bucardo/tail_n_mail#33]
I have put the tail_n_mail  file in /var/temp folder for testing on ubuntu. 

When I run below command I get below message. 
perl tail_n_mail tnm.config.txt

![image](https://user-images.githubusercontent.com/14271741/54997971-0588a800-4ff3-11e9-963c-48d06d22c915.png)
 
However I do not get any mail or output on commandprompt for any errors. 
Did I miss anything ?

**Comment by turnstep** [comment]
Looks like it is expecting to find the file /var/log/postgres/postgresql-10-main.log, but that does not exist. Double check the file locations and names.

**Comment by turnstep** [comment]
Closing as non-issue
