### ISSUE TITLE
Error running tail_n_mail with LOG_LINE_PREFIX set

### ISSUE THREAD

**Issue by cnemelka** [bucardo/tail_n_mail#34]
.tailnmailrc

log_line_prefix='%m appname=%a,user=%u,db=%d,pid=%p,txid=%x,vtxid=%v'

Error when running:
Can't use string ("'%m appname=%a,user=%u,db=%d,pid"...) as a HASH ref while "strict refs" in use at tail_n_mail line 3734.

**Comment by turnstep** [comment]
The format should be:
```
LOG_LINE_PREFIX: '%m appname=%a,user=%u,db=%d,pid=%p,txid=%x,vtxid=%v'
```

**Comment by turnstep** [comment]
If the error still occurs, please let us know.

**Comment by cnemelka** [comment]
fixed
