### ISSUE TITLE
Config files don't remain static?

### ISSUE THREAD

**Issue by joecreighton** [bucardo/tail_n_mail#36]
Upgrading to 3.1.0 from an old 1.31.x.  Found note in 3.0 changes doc that "Config files are now static, and will not get rewritten."  Ran 3.1.0 for a few days and fresh config.state files are present for each cluster.  Compared config with config.state files to determine what's redundant.  In my case, I saw

config: MAILSUBJECT, INHERIT, FILE1, LASTFILE1, OFFSET1
config.state: FILE1, LASTFILE1, ROTATEFILEMODTIME1, OFFSET1

Edited config to only have MAILSUBJECT, INHERIT which should make it good for git inclusion.  Ran "select 2/0;" in one cluster to generate error.  Reran TNM: no errors, mail received about division by zero error, but the config file was rewritten to as it was before.

**Comment by turnstep** [comment]
Not sure what is happening here: are you sure you are running the new version? There is only a single write in the new tail_n_mail:
```perl
4062:    open my $sfh, '>', $statefile or die qq{Could not write "$statefile": $!\n};
```

**Comment by joecreighton** [comment]
Thanks for the confirmation.  I dug further and found there were *two* calls to tail_n_mail happening: one to the newest version and one to the old version.  When I disabled the old one, things worked as expected: the config file remained static and the config.state file updated each call.  Apologies for the red herring.

**Comment by turnstep** [comment]
Glad it worked out. Try version  3.2.0, just released!
