### ISSUE TITLE
Argument "1,329" isn't numeric in printf at tail_n_mail line 3803.

### ISSUE THREAD

**Issue by joecreighton** [bucardo/tail_n_mail#37]
Email from cron contained this one-liner.
Using tail_n_mail.3.2.0
TNM email was still sent at same timestamp as cron email; the "Matches" line corresponds to error:

Date: Sat Jan 30 08:15:02 2021 CST
Host: XXXX
Unique items: 1
Matches from 20210130.log: 1,329

Thanks.

**Comment by jonjensen** [comment]
@joecreighton Thanks for the report. Bug fixed in commit 111ae38de36d1d468c03b1df7bfd490c64edf222.
