### ISSUE TITLE
Not escaping parentheses

### ISSUE THREAD

**Issue by keithf4** [bucardo/tail_n_mail#8]
Parentheses are still not getting escaped around log line options and it's causing lines not to be matched. I'd reported this back around version 1.19.3, but it's still happening with the latest version (1.25.1)

For example, this does not match
log_line_prefix = '%t (%r) [%p]: [%l-1] user=%u,db=%d '

But this does
log_line_prefix = '%t [%r] [%p]: [%l-1] user=%u,db=%d '

**Comment by turnstep** [comment]
Thanks for the report, I made the escaping a little more global as of 7e322419fd791ba3fe4246e63cd2f8fb4f355e63, hopefully that fixes the issue.
